### PR TITLE
Use refinements to work with native classes

### PR DESCRIPTION
**Pull request by vlaimirus**
I've noticed that refinements is not used for changing base classes. What do you think?

### CODE REVIEW

**Comment by vlaimirus** [comment]
Huh. Checks failed... are they working correctly right now?

**Comment by raventid** [comment]
No, not yet. I'm going to fix it later next week, so don't look at fails.
You can run tests manually with `rake test`. I don't see you changed code,
which uses this array method (if any). Are you sure everything's still
working? :)

2016-04-04 1:51 GMT+03:00 Vladimir Rogachev notifications@github.com:

> Huh. Checks failed... are they working correctly right now?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/raventid/dhh/pull/4#issuecomment-205070044

## 

С уважением, Кулеш Ю.Д.

**Comment by raventid** [comment]
Ping :question:

**Comment by raventid** [comment]
Hey, I've decided to merge this as it is. I've decided to use refinements for this project.

Thank you for the idea)

**Pull request merged**
